### ISSUE TITLE
OAuth2 SignIn error at first time

### ISSUE THREAD

**Issue by ariasfernando** [google/google-api-javascript-client#305]
Hello everyone!

I'm working with Google Sign-In JavaScript through Google OAuth2 API:

```
var googleAuth = {};
gapi.load('auth2', function(){
        googleAuth = gapi.auth2.init({ client_id: [MY_CLIENT_ID] });
});
```
When I try to make signing up a user, meaning that he needs to authorize Google to use my app, through `signIn()` method...

```
var options = new gapi.auth2.SigninOptionsBuilder();
options.setPrompt('consent');
googleAuth.signIn(options);
```
The Promise object that `signIn()` returns resolves with an error:

```
Object {type: "tokenFailed", idpId: "google", error: "IMMEDIATE_FAILED"}
```

 I checked all [reference](https://developers.google.com/identity/sign-in/web/reference) and I could not found anything about this error. Only about **IMMEDIATE_FAILED** but it should happen in case API forces user to signin without prompting about authorization using option **Prompt: none** ( that's what I'm setting Prompt: consent, to ensure that is not related with it ) and user had not given permissions to the application.

I couldn't even resolve it o find a pattern _playing_ with SignIn options.

Could anybody help me? 

Thanks! :)

**Comment by TMSCH** [comment]
@ariasfernando I am not able to reproduce the issue :( could you open the Network logs, look for requests to `https://accounts.google.com/o/oauth2/iframerpc`, and copy paste the full URLs as well as the responses?

**Comment by ariasfernando** [comment]
Yes, of course @TMSCH  !

On window load:
```
https://accounts.google.com/o/oauth2/iframerpc?action=issueToken&response_type=token%20id_token&scope=openid%20profile%20email&client_id=796353764992-ch0auepb68jb9u6h2k0806nqsdkui8f9.apps.googleusercontent.com&login_hint=AJDLj6JUa8yxXrhHdWRHIV0S13cA0dcPNS-3tcbozuygTHev2EKfrFyCUdD06219ov_dIWI6_VS_yIML5khw9hquotsQZviF2w&ss_domain=http%3A%2F%2Flocalhost%3A4200&origin=http%3A%2F%2Flocalhost%3A4200
```
`{"error":"IMMEDIATE_FAILED","detail":"Not all scopes are approved."}`

**Comment by AlokGupta007** [comment]
Hi, I am facing this error 

Google.initialize({
clientID : "client_id",
});

And the error is
{"type":"error","source":{"bubbleParent":true,"apiName":"Ti.Module","invocationAPIs":[],"_events":{"connect":{},"error":{},"disconnect":{},"login":{}}},"message":null,"status":10,"success":false,"bubbles":false,"cancelBubble":false}

Please help me out this problem.

**Comment by TMSCH** [comment]
@ariasfernando do you go through a sign-in flow in a popup, before the promise rejects? Could you share a minimal snippet of code that reproduces the issue? Thanks!

@AlokGupta007 this is not the correct library. Please head to the [doc](https://developers.google.com/identity/sign-in/web/) for a Guide on Google Sign-In.

**Comment by ariasfernando** [comment]
Yes, of course @TMSCH. Note that I'm used a code based on the [example showed in documentation](https://developers.google.com/identity/sign-in/web/build-button), and it happens only at first time that an account tries to sign in. If I reload page after error happens, I can get the user data object. Pretty strange.

```<html>
<head>
  <link href="https://fonts.googleapis.com/css?family=Roboto" rel="stylesheet" type="text/css">
  <script src="https://apis.google.com/js/api:client.js"></script>
  <script>
  var googleUser = {};
  var startApp = function() {
    gapi.load('auth2', function(){
      // Retrieve the singleton for the GoogleAuth library and set up the client.
      auth2 = gapi.auth2.init({
        client_id: '726926616687-0a3dg1mb11l2p33h2sar9qh47ill993a.apps.googleusercontent.com',
        cookiepolicy: 'single_host_origin',
        // Request scopes in addition to 'profile' and 'email'
        //scope: 'additional_scope'
      });
      attachSignin(document.getElementById('customBtn'));
    });
  };

  function attachSignin(element) {
    console.log(element.id);
    auth2.attachClickHandler(element, {},
        function(googleUser) {
          document.getElementById('name').innerText = "Signed in: " +
              googleUser.getBasicProfile().getName();
        }, function(error) {
          alert(JSON.stringify(error, undefined, 2));
        });
  }
  </script>
  </style>
  </head>
  <body>
  <!-- In the callback, you would hide the gSignInWrapper element on a
  successful sign in -->
  <div id="gSignInWrapper">
    <span class="label">Sign in with:</span>
    <div id="customBtn" class="customGPlusSignIn">
      <span class="icon"></span>
      <span class="buttonText">Google</span>
    </div>
  </div>
  <div id="name"></div>
  <script>startApp();</script>
</body>
</html>
```

**Comment by TMSCH** [comment]
@ariasfernando I still cannot reproduce the issue :( What browser are you using? Are you using Incognito mode?

**Comment by ariasfernando** [comment]
I'm using Chrome 59 and I'm not using Incognito mode

**Comment by serpalinkieweicz** [comment]
Hi, I'm facing the axactly same problem with exactly same example code of the @ariasfernando.

I've noted that it happens even at the example in the docs: https://developers.google.com/identity/sign-in/web/build-button

To reproduce the issue, please follow these steps: 

1. Click the button as marked below:
![image](https://user-images.githubusercontent.com/11880410/27150991-8c623d16-511f-11e7-9943-4f85abfedaa5.png)

2. Choose the account to log in:
![image](https://user-images.githubusercontent.com/11880410/27151083-d34d7114-511f-11e7-825b-cbe6dec7d169.png)

3. You will get this error:
![image](https://user-images.githubusercontent.com/11880410/27151126-f5dd032a-511f-11e7-9bde-5e8a88a1ef81.png)

4. If you don't get the error, go to the [Connected Apps](https://myaccount.google.com/permissions) and remove permission of the Google Sign-In Demo. So restart by the first step again.

![image](https://user-images.githubusercontent.com/11880410/27151219-4941bbe6-5120-11e7-8135-d006947b8b61.png)

**Comment by TMSCH** [comment]
@serpalinkieweicz thanks for mentioning this and giving all these info. Did you try signing in with the @gmail.com or @outlook.com account? I tried the exact same protocol and don't observe it.

@ariasfernando where you maybe using a non @gmail.co account?

**Comment by ariasfernando** [comment]
Hi @TMSCH! Sorry for the delay, I'm using a @gmail.com account, which obviously is not the same that the account which is owner of the Google App whose client ID I'm using for OAuth.

Thank you @serpalinkieweicz for the info, you're having the exactly same issue.

**Comment by serpalinkieweicz** [comment]
I thank you for the help, @TMSCH. 

The problem is not happening to me anymore.

Is it possible that this problem is ocurred only here in Brazil?

I've read several news about a Google DNS system failure in Brazil this week. Do you think our problem might be related to this?

And... answering your ask: I've tried with the both accounts. The @outlook.com is not a gmail account, but is a google account.

@ariasfernando, the problem was solved to you too?

**Comment by ariasfernando** [comment]
No, I just tested and still having the issue :frowning_face:

**Comment by TMSCH** [comment]
@ariasfernando could you try the flow in an incognito window, after removing the app's permission g( as @serpalinkieweicz explains in a previous comment)?

**Comment by serpalinkieweicz** [comment]
The error came back today.

**Comment by TMSCH** [comment]
@serpalinkieweicz sorry to hear the issue is still present. We are currently investigating the root cause.

**Comment by serpalinkieweicz** [comment]
I noticed that the error does not happen in IE10.

**Comment by TMSCH** [comment]
@serpalinkieweicz what other browser have you tested? Does it consistently work on IE10? (or only most of the time)

**Comment by serpalinkieweicz** [comment]
I tested it in IE10, IE11, Chrome 58, FF 53 and Safari 10. 

In IE10 always works because the URL that opens in the popup is different from the others: 

![image](https://user-images.githubusercontent.com/11880410/27406276-c825e45c-56aa-11e7-9b06-b7f203908992.png)



While in others browsers appears like that: 

![image](https://user-images.githubusercontent.com/11880410/27406386-0bfa4574-56ab-11e7-95d5-9e4ee51278df.png)

**Comment by TMSCH** [comment]
@serpalinkieweicz thanks again for all the info! In the browser that have the issue, when you reload the page, is the user directly signed in? (you can see that in the blue button in this section: https://developers.google.com/identity/sign-in/web/build-button#customizing_the_automatically_rendered_sign-in_button_recommended)

**Comment by serpalinkieweicz** [comment]
@TMSCH, that only happens when I'm logged in. :confused:

**Comment by serpalinkieweicz** [comment]
Wait, no... 

Doesn't matter if I'm signed in on my google account or not. 

It only happens when I have not this permission: 

![image](https://user-images.githubusercontent.com/11880410/27409541-56437db4-56b8-11e7-9c5c-ed4c46334f18.png)

**Comment by TMSCH** [comment]
@serpalinkieweicz do you have an application where you can change the code where you reproduce the issue? If so, could you add `scope: 'https://www.googleapis.com/auth/drive.readonly'` in the `gapi.auth2.init` call?
Let me know then if you observe the issue.

**Comment by serpalinkieweicz** [comment]
Dude, it worked! :tada: :confetti_ball: :balloon: :fireworks:

**Comment by serpalinkieweicz** [comment]
Thanks a lot! 

I just thought it was weird cause it was asking for Google Drive's files readonly permission. And I don't need to read these files.

**Comment by TMSCH** [comment]
@serpalinkieweicz happy to hear that! This means we have identified the root cause of the bug you observed. We are working on a fix that will remove the need of requesting an additional scope. Sorry about the inconvenience in the meantime.

**Comment by serpalinkieweicz** [comment]
Right, thanks for your patience and sorry about my poor english. :laughing:

**Comment by feuerwelt** [comment]
Is this issue already fixed? Or there's another workaround in the meantime, instead of this "google drive scope" approach? Because I'm experiencing the same issue and simply don't know what else to do to solve it .. ://

**Comment by TMSCH** [comment]
@feuerwelt we are currently working on a fix. Unfortunately there is no other workaround, as this is due to latency issues that can be observed in areas where data centers are more scarce.

**Comment by Artenes** [comment]
@TMSCH Just reporting that I am also facing the same problem. Followed the tutorial from https://developers.google.com/identity/sign-in/web/build-button and the login always fails in the first attempt, when the user is trying to connect with my application for the first time. In the next attempts the login works without a problema. And I am also from Brazil like @serpalinkieweicz. If I can help in something just ask.

**Comment by feuerwelt** [comment]
@Artenes Don't know how critical google login is for your application, but if you really need to use it while this issue is not fixed, try asking for any scope in this list: https://developers.google.com/identity/protocols/googlescopes. Maybe your users won't complain if you ask for some scope like `https://www.googleapis.com/auth/youtube.readonly`. At least, this is what I'm counting on for my own projects. ;)

**Comment by serpalinkieweicz** [comment]
@feuerwelt But by requesting an additional scope to make it public, you'll need to [submit](https://support.google.com/code/contact/oauth_app_verification) your application for review by Google. Otherwise the users will have to enter in the [Risky Access Group](https://groups.google.com/forum/#!forum/risky-access-by-unreviewed-apps) to access your app.

**Comment by lcssanches** [comment]
Same here. First time always fail.

I tried to call a second time but I'm getting another error
```
auth2 = gapi.auth2.getAuthInstance();
auth2.signIn( { immediate: false } );
//result: {error: "popup_closed_by_user"}
```


I'm on Brazil too.

**Comment by lcssanches** [comment]
Without immediate parameter does not work too.

```
auth2 = gapi.auth2.getAuthInstance();
auth2.signIn( );
//result: {error: "popup_closed_by_user"}
```

**Comment by chadjaros** [comment]
I'm in Chicago testing our Google Sign In implementation, and I saw this yesterday with a couple of test accounts. However, I can no longer reproduce this even after removing the App's permissions through the account screens.

**Comment by lcssanches** [comment]
Not working here.

@chadjaros can you post your code?

**Comment by chadjaros** [comment]
I'm pulling in `https://apis.google.com/js/auth2.js` through bower because I'm using an angular app and for some reason `gapi.load` silently fails in google incognito when we pull in `https://apis.google.com/js/client.js`.

// Init the library
// this._gapi is the global gapi instance injected into the angular service

    this._gapi.load('auth2', () => {
      this._googleAuth = this._gapi.auth2.init({
        client_id: this._environment.google.auth.clientId
      });
    });

//then

    this._googleAuth.signIn()
      .then(() => {
         //... finish logging in with our server

We're using a custom button.

**Comment by araujojohnny** [comment]
Any update on this?
I'm facing the same problem. The signIn() result is always an error.

**Comment by TMSCH** [comment]
@silvajonathan could you post a snippet of code to reproduce the issue? I am not sure to understand properly what you're encountering.

**Comment by silvajonathan** [comment]
In my case it is a Angular 4 application.

I'm loading the auth2/client objects along with my backend Endpoints client before the angular bootstrap:

```typescript
const gapi = window['gapi'];
gapi.load('client:auth2', function loadGapiCallback() {
  gapi.client.init({
    client_id: 'MYCLIENTID',
    scope: 'MY SCOPES'
  }).then(function clientInitResolve() {
    gapi.client.load('my_api_name', 'my_api_version', function loadApiCallback() {
      platformBrowserDynamic().bootstrapModule(AppModule);
    }, '_ah/api')
  });
})
```

Inside the Angular application, after it loads, I need to make an authorized request with gapi and it looks like this:
```typescript
const gapi = window['gapi'];
const isSignedIn = gapi.auth2.getAuthInstance().isSignedIn.get();
if(isSignedIn) {
  gapi.client.myapi.resource.endpoint().then(() => {/*do stuff here*/});
}else {
  gapi.auth2.getAuthInstance().signIn({
    ux_mode: 'redirect',
    redirect_uri: 'http://localhost:4200/auth2callback.html',
    prompt: 'consent'
  });
}
```
The oauth2callback.html file only redirects back the user to the `/#/` path.

With this `ux_mode` value the browser redirects the current browser tab to Google sign in page and returns back to my app when it finishes. After that, the whole flow restart: the gapi initialization; angular bootstrap and my authorized request attempt. The problem is that even after the first sign in attempt gapi isSignedIn.get() keeps returning false, making the user get redirected to Google sign in again.

Sometimes it happens three times before isSignedIn.get() return true.
I'm wondering if there is anything else to do on the oauth2callback.html file, since it is called with an `id_token` attached to the url.

**Comment by TMSCH** [comment]
@silvajonathan thanks for the explanation. It seems to be the same problem than already mentioned, applied to the redirect mode. We are still looking into it - we should have fixed it in the case where the user perform the sign-in flow in the popup (or within the redirected page). However, it seems to still be an issue when the user just clicks on one of their Google account.

**Comment by TMSCH** [comment]
@ariasfernando @chadjaros @serpalinkieweicz @Artenes @feuerwelt @silvajonathan a fix is now live in production. Could you test on your end and make sure you don't observe the problem anymore? Thanks!

**Comment by lcssanches** [comment]
Not working here.

{error_subtype: "access_denied", error: "immediate_failed"}

Also, I note that the application is only connected to my account on the second try, after immediate_failed.

**Comment by TMSCH** [comment]
@lcssanches I may have talked slightly too fast, my bad. The production push is not yet at 100%. I'll ping the thread when it is!

**Comment by serpalinkieweicz** [comment]
It has worked! Thanks a lot, @TMSCH. I'll try again in a few hours to make sure if the problem is not occurring anymore. Thanks again.

**Comment by TMSCH** [comment]
@serpalinkieweicz Great! @lcssanches could you try again now? It should be completely rolled out.

**Comment by feuerwelt** [comment]
It worked @TMSCH! Thanks a lot! :D

**Comment by TMSCH** [comment]
Great! Closing the issue now :)

**Comment by Artenes** [comment]
@TMSCH Just reporting that the problem is gone, thanks a lot for your support!

**Comment by lcssanches** [comment]
Sorry for the delay, it's working. Thanks!!!

**Comment by TMSCH** [comment]
Great to hear that! Thanks for the reports.
